create or replace view COM.DML_PROCESS_LOG_VW(
	EXECUTION_ID,
	ETL_NAME,
	ETL_TASK_NAME,
	EXECUTED_SP,
	EXECUTION_STATUS,
	QUERY_ID,
	QUERY_TYPE,
	START_TIME,
	END_TIME,
	UPLOADED_DATE,
	LOAD_DATE,
	DESTINATION,
	ROWS_INSERTED,
	ROWS_UPDATED,
	ROWS_DELETED,
	TOTAL_ELAPSED_TIME,
	FAIL_CODE,
	ERROR_MESSAGE,
	STACK_TRACE,
	ERROR_STATE,
	USER_NAME
) as
SELECT
    EXECUTION_ID,
    ETL_NAME,
    ETL_TASK_NAME,
    EXECUTED_SP,
    DETAILS_AFTER_EXEC :EXECUTION_STATUS :: VARCHAR AS EXECUTION_STATUS,
    DETAILS_AFTER_EXEC :QUERY_ID :: VARCHAR AS QUERY_ID,
    DETAILS_AFTER_EXEC :QUERY_TYPE :: VARCHAR AS QUERY_TYPE,
    DETAILS_AFTER_EXEC :START_TIME :: DATETIME AS START_TIME,
    DETAILS_AFTER_EXEC :END_TIME :: DATETIME AS END_TIME,
    DETAILS_AFTER_EXEC :UPLOADED_DATE :: VARCHAR AS UPLOADED_DATE,
    DETAILS_AFTER_EXEC :UPLOADED_DATE :: VARCHAR AS LOAD_DATE,
    DETAILS_AFTER_EXEC :DESTINATION :: VARCHAR AS DESTINATION,
    DETAILS_AFTER_EXEC :ROWS_INSERTED :: VARCHAR AS ROWS_INSERTED,
    DETAILS_AFTER_EXEC :ROWS_UPDATED :: VARCHAR AS ROWS_UPDATED,
    DETAILS_AFTER_EXEC :ROWS_DELETED :: VARCHAR AS ROWS_DELETED,
    DETAILS_AFTER_EXEC :TOTAL_ELAPSED_TIME :: VARCHAR AS TOTAL_ELAPSED_TIME,
    DETAILS_AFTER_EXEC :FAIL_CODE :: VARCHAR AS FAIL_CODE,
    DETAILS_AFTER_EXEC :MESSAGE :: VARCHAR AS ERROR_MESSAGE,
    DETAILS_AFTER_EXEC :STACK_TRACE :: VARCHAR AS STACK_TRACE,
    DETAILS_AFTER_EXEC :STATE :: VARCHAR AS ERROR_STATE,
    DETAILS_AFTER_EXEC :USER_NAME :: VARCHAR AS USER_NAME
FROM
    COM.PROCESS_AUDIT_LOG LOG
WHERE
    EXECUTED_SP <> 'COM.GENERIC_LOAD_STG_TABLE_SP'
    and (
        (
            QUERY_TYPE NOT IN ('COPY', 'CREATE_TABLE_AS_SELECT')
        )
        OR (QUERY_TYPE IS NULL)
    )
    AND EXECUTION_STATUS IS NOT NULL
ORDER BY
    START_TIME DESC;