create or replace view COM.MASTER_LOG_VW(
	EXECUTION_ID,
	ETL_NAME,
	ETL_TASK_NAME,
	EXECUTED_SP,
	STATUS,
	START_TIME,
	END_TIME
) as
SELECT
    EXECUTION_ID,
    ETL_NAME,
    ETL_TASK_NAME,
    EXECUTED_SP,
    STATUS,
    START_TIME,
    END_TIME
FROM
    COM.MASTER_AUDIT_LOG
ORDER BY
    START_TIME DESC,
    END_TIME DESC;