CREATE OR REPLACE FUNCTION COM."GENERIC_GET_VALUE_WITH_DEFAULT_SP"(JSON_OBJECT OBJECT, JSON_KEY VARCHAR, DEFAULT_VALUE VARCHAR)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
AS $$
  try{
  var JSON_VALUE = JSON_OBJECT[JSON_KEY];
  if (JSON_VALUE == undefined){
  return DEFAULT_VALUE;
  }
  return JSON_VALUE;
  }
  catch (err){
  return DEFAULT_VALUE;
  }  
$$;