CREATE OR REPLACE FUNCTION COM.GET_TEXT_COLUMN_LENGTH_UD("DB_NM" VARCHAR(16777216), "SCHEMA_NM" VARCHAR(16777216), "TABLE_NM" VARCHAR(16777216), "COLUMN_NM" VARCHAR(16777216))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS $$
SELECT CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = db_nm
AND TABLE_SCHEMA= schema_nm
AND TABLE_NAME = table_nm
AND COLUMN_NAME = column_nm
AND DATA_TYPE = 'TEXT'
$$;