CREATE OR REPLACE FUNCTION COM.INT_CHK_UD("COLNAME" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
AS $$
    var x = parseFloat(COLNAME);
    return !isNaN(COLNAME) && (x | 0) === x;
$$;