create or replace TABLE COM.SCD_MAPPING_TABLE (
	RULE_ID NUMBER(38,0) NOT NULL autoincrement,
	SRC_SCHEMA VARCHAR(30),
	SRC_TABLE VARCHAR(100),
	TGT_SCHEMA VARCHAR(30),
	TGT_TABLE VARCHAR(100),
	PRIMARY_KEY_COLS VARCHAR(200),
	SCD_COLS VARCHAR(1000),
	JOB_NAME VARCHAR(100),
	IS_DELETE_DATA VARCHAR(3),
	IS_CONDITIONAL_DELETE VARCHAR(3),
	CREATED_BY VARCHAR(30),
	CREATED_DATE DATE,
	primary key (RULE_ID)
);