CREATE OR REPLACE FUNCTION COM."GENERIC_DATA_HASH_UD"(INPUT_VAL VARCHAR)
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS $$
SELECT IFF(INPUT_VAL IS NULL OR INPUT_VAL='', NULL,XXHASH64(0,TO_BINARY(CONCAT(INPUT_VAL,'bgh17sjo9a'),'utf-8')))
$$;