create or replace TABLE COM.DQ_ERROR_TABLE (
	DATABASE_NAME VARCHAR(100),
	SCHEMA_NAME VARCHAR(100),
	TABLE_NAME VARCHAR(100),
	ERROR_INFO VARIANT,
	EXECUTION_ID VARCHAR(100)
);
create or replace TABLE COM.SAVE_COPY_ERROR (
	ERROR VARCHAR(16777216),
	FILE VARCHAR(16777216),
	LINE NUMBER(18,0),
	CHARACTER NUMBER(18,0),
	BYTE_OFFSET NUMBER(18,0),
	CATEGORY VARCHAR(16777216),
	CODE NUMBER(18,0),
	SQL_STATE VARCHAR(16777216),
	COLUMN_NAME VARCHAR(16777216),
	ROW_NUMBER NUMBER(18,0),
	ROW_START_LINE NUMBER(18,0),
	REJECTED_RECORD VARCHAR(16777216),
	EXECUTION_ID VARCHAR(100)
);
create or replace TABLE COM.TEST_RESULT (
	COLUMN_NAME VARCHAR(100),
	SRC_NAME VARCHAR(300),
	TGT_NAME VARCHAR(300),
	MIN VARCHAR(100),
	MAX VARCHAR(100),
	AVG VARCHAR(100),
	SUM VARCHAR(100),
	COUNT VARCHAR(30),
	DISTINCT_COUNT VARCHAR(30),
	EXECUTION_ID VARCHAR(100)
);
CREATE OR REPLACE TABLE COM.BLOCK_DRIVER(
    TABLE_NAME VARCHAR(100),
	FREQUENCY VARCHAR(100),
    BLOCK_NAME VARCHAR(100),
    BLOCK_TYPE VARCHAR(100)
);
create or replace view COM.DAILY_MISSED_TABLES_VW as(
	select block.table_name,block.block_type,block.block_name from "COM"."BLOCK_DRIVER" block
	left join "COM"."TOTAL_LOADING_VW" vw
	on block.table_name = vw.RAW_TABLE_NAME
	and vw.RAW_PARTITION_LOADED = current_date()-1
	where vw.raw_table_name is null
	and block.frequency = 'DAILY'
);
