CREATE OR REPLACE FUNCTION COM.GENERIC_GET_VALUE_WITH_DEFAULT_SP("JSON_OBJECT" OBJECT, "JSON_KEY" VARCHAR(16777216), "DEFAULT_VALUE" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
AS $$
  try{
  var JSON_VALUE = JSON_OBJECT[JSON_KEY];
  if (JSON_VALUE == undefined){
  return DEFAULT_VALUE;
  }
  return JSON_VALUE;
  }
  catch (err){
  return DEFAULT_VALUE;
  }  
$$;