USE ROLE SYSADMIN; 

CREATE FILE FORMAT COM.PARQUET_FF
TYPE = 'PARQUET' 
COMPRESSION = 'AUTO' 
BINARY_AS_TEXT = FALSE
COMMENT = 'PARQUET FILE FORMAT TO LOAD THE FILES IN S3 WITH DEFAULT SNAPPY COMPRESSION';

CREATE FILE FORMAT COM.ORC_FF
TYPE = 'ORC' 
COMMENT = 'ORC FILE FORMAT TO LOAD THE FILES IN S3 WITH DEFAULT COMPRESSION';